-- SQL to populate GCPD db

-- records for crimes
insert into crimes(name) values('Murder');
insert into crimes(name) values('Assault');
insert into crimes(name) values('Battery');
insert into crimes(name) values('Rape');
insert into crimes(name) values('Robbery');
insert into crimes(name) values('Burglary');
insert into crimes(name) values('Theft');
insert into crimes(name) values('Drug Possession');
insert into crimes(name) values('Kidnapping');
insert into crimes(name) values('Arson');
insert into crimes(name) values('Conspiracy');
insert into crimes(name) values('Extortion');
insert into crimes(name) values('Fraud');
insert into crimes(name) values('Vandalism');
insert into crimes(name) values('Accessory');
insert into crimes(name) values('Manslaughter');
	
-- records for units
insert into units(name) values('Major Crimes');
insert into units(name) values('SWAT');
insert into units(name) values('Quick Response Team');
insert into units(name) values('Homicide');
insert into units(name) values('Patrol');
insert into units(name) values('Internal Affairs');

-- records for officers
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('Jim', 'Gordon', 'Commissioner', null, '2000-01-01');
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('John', 'Blake', 'Detective Sergeant', 1, '2008-01-03');
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('Maggie', 'Sawyer', 'Captain', 1, '2004-12-05');
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('Josh', 'Azeveda', 'Detective', 1, '2009-05-01');
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('Roman', 'Cavallo', null, 5, '2011-02-01');
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('George', 'Bilbao', 'Lieutenant', 4, '2008-6-01');
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('Nora', 'Fields', 'Supervisor', null, '2002-03-01');
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('Harvey', 'Bullock', 'Detective', 1, '2000-08-01');
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('Gillian', 'Loeb', null, 5, '2000-01-01');
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('Kelvin', 'Mao', null, 2, '2011-01-01');
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('Jordan', 'Rich', null, 5, '2012-01-01');
insert into officers(first_name, last_name, rank, unit_id, joined_gcpd_on) values('Raymond', 'Willis', 'Detective', 6, '2009-11-01');
	
-- records for criminals
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Selina', 'Kyle', 'Catwoman', false, false);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Edmund', 'Dorrance', 'Bane', true, true);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Jack', 'Napier', 'Joker', true, true);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Victor', 'Fries', 'Mr. Freeze', true, true);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Oswald', 'Cobblepot', 'Penguin', true, true);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Edward', 'Nigma', 'Riddler', true, true);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Jonathon', 'Crane', 'Scarecrow', true, true);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Harvey', 'Dent', 'Two Face', true, true);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Salvatore', 'Maroni', null, false, false);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Yuri', 'Chechen', null, false, false);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Michael', 'Gambol', null, false, false);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Carmine', 'Falconi', null, true, false);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Joe', 'Chill', null, true, false);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('John', 'Daggett', null, false, false);
insert into criminals(first_name, last_name, alias, convicted_felon, super_criminal) values('Ras', 'al Ghul', null, false, true);


-- records for cases
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 1', 1,(select date(now() - trunc(random()*90) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 2', 1,(select date(now() - trunc(random()*180) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 3', 1,(select date(now() - trunc(random()*180) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 4', (select trunc(random()*14+1)),(select date(now() - trunc(random()*180) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 5', (select trunc(random()*14+1)),(select date(now() - trunc(random()*180) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 6', (select trunc(random()*14+1)),(select date(now() - trunc(random()*180) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 7', (select trunc(random()*14+1)),(select date(now() - trunc(random()*180) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 8', (select trunc(random()*14+1)),(select date(now() - trunc(random()*180) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 9', (select trunc(random()*14+1)),(select date(now() - trunc(random()*180) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 10', (select trunc(random()*14+1)),(select date(now() - trunc(random()*180) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 11', (select trunc(random()*14+1)),(select date(now() - trunc(random()*180) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 12', (select trunc(random()*14+1)),(select date(now() - trunc(random()*360) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 13', (select trunc(random()*14+1)),(select date(now() - trunc(random()*360) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 14', (select trunc(random()*14+1)),(select date(now() - trunc(random()*360) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 15', (select trunc(random()*14+1)),(select date(now() - trunc(random()*360) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 16', (select trunc(random()*14+1)),(select date(now() - trunc(random()*360) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 17', (select trunc(random()*14+1)),(select date(now() - trunc(random()*700) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 18', (select trunc(random()*14+1)),(select date(now() - trunc(random()*700) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 19', (select trunc(random()*14+1)),(select date(now() - trunc(random()*700) * '1 day'::interval)),false,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 20', (select trunc(random()*14+1)),(select date(now() - trunc(random()*700) * '1 day'::interval)),true,true);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 21', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 22', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 23', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 24', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 25', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 26', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 27', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 28', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 29', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 30', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 31', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 32', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 33', (select trunc(random()*10+2)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 34', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 35', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 36', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 37', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 38', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 39', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 40', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 41', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 42', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 43', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 44', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 45', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 46', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 47', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),true,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 48', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 49', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);
insert into cases(title,crime_id,date_opened,solved,batman_involved) values('Case 50', (select trunc(random()*12+1)),(select date(now() - trunc(random()*500) * '1 day'::interval)),false,false);

-- records for assignments
insert into assignments(case_id, officer_id, start_date, end_date) values (1,2,'2012-09-09','2012-10-01'); 
insert into assignments(case_id, officer_id, start_date, end_date) values (1,7,'2012-09-09','2012-10-01');
insert into assignments(case_id, officer_id, start_date, end_date) values (1,1,'2012-09-09','2012-10-01'); 
insert into assignments(case_id, officer_id, start_date, end_date) values (2,3,'2012-05-12','2012-08-01');
insert into assignments(case_id, officer_id, start_date, end_date) values (2,7,'2012-05-12','2012-08-01');
insert into assignments(case_id, officer_id, start_date, end_date) values (2,1,'2012-05-12','2012-08-01');
insert into assignments(case_id, officer_id, start_date, end_date) values (3,2,'2012-06-26','2012-08-15');
insert into assignments(case_id, officer_id, start_date, end_date) values (3,7,'2012-06-26','2012-08-15');
insert into assignments(case_id, officer_id, start_date, end_date) values (4,2,'2012-08-12','2012-08-30');
insert into assignments(case_id, officer_id, start_date, end_date) values (5,4,'2012-07-15','2012-09-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (5,1,'2012-09-15','2012-09-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (6,2,'2012-06-24','2012-08-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (7,6,'2012-08-05','2012-09-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (7,1,'2012-09-05','2012-09-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (8,2,'2012-08-15','2012-09-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (9,2,'2012-07-20','2012-10-01'); 
insert into assignments(case_id, officer_id, start_date, end_date) values (10,8,'2012-07-09','2012-08-01');
insert into assignments(case_id, officer_id, start_date, end_date) values (10,1,'2012-08-01','2012-09-01'); 
insert into assignments(case_id, officer_id, start_date, end_date) values (11,2,'2012-08-12','2012-10-04');
insert into assignments(case_id, officer_id, start_date, end_date) values (11,1,'2012-08-12','2012-10-04');
insert into assignments(case_id, officer_id, start_date, end_date) values (12,1,'2012-08-22','2012-10-15');
insert into assignments(case_id, officer_id, start_date, end_date) values (12,2,'2012-08-26','2012-10-15');
insert into assignments(case_id, officer_id, start_date, end_date) values (13,2,'2012-05-09','2012-06-15');
insert into assignments(case_id, officer_id, start_date, end_date) values (14,8,'2012-08-12','2012-08-30');
insert into assignments(case_id, officer_id, start_date, end_date) values (15,5,'2012-04-20','2012-09-11');
insert into assignments(case_id, officer_id, start_date, end_date) values (16,2,'2012-06-15','2012-07-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (17,2,'2011-06-14','2011-06-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (18,6,'2012-10-12','2012-10-17');
insert into assignments(case_id, officer_id, start_date, end_date) values (18,1,'2012-10-12','2012-10-17');
insert into assignments(case_id, officer_id, start_date, end_date) values (19,9,'2011-12-07','2012-09-15');
insert into assignments(case_id, officer_id, start_date, end_date) values (20,2,'2011-03-02','2012-01-04');	
insert into assignments(case_id, officer_id, start_date, end_date) values (21,2,'2011-12-09','2012-10-01'); 
insert into assignments(case_id, officer_id, start_date, end_date) values (22,7,'2011-08-15','2011-10-02');
insert into assignments(case_id, officer_id, start_date, end_date) values (23,7,'2011-09-09','2011-10-01'); 
insert into assignments(case_id, officer_id, start_date, end_date) values (24,3,'2011-10-22','2011-12-01');
insert into assignments(case_id, officer_id, start_date, end_date) values (26,4,'2012-09-12','2012-10-01');
insert into assignments(case_id, officer_id, start_date, end_date) values (27,2,'2012-08-26','2012-10-15');
insert into assignments(case_id, officer_id, start_date, end_date) values (28,7,'2011-12-13','2011-12-25');
insert into assignments(case_id, officer_id, start_date, end_date) values (29,2,'2012-05-20','2012-08-30');
insert into assignments(case_id, officer_id, start_date, end_date) values (30,4,'2012-04-15','2012-09-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (31,4,'2012-07-31','2012-09-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (32,2,'2011-07-14','2011-08-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (33,6,'2012-01-25','2012-03-14');
insert into assignments(case_id, officer_id, start_date, end_date) values (34,2,'2012-07-05','2012-09-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (35,2,'2012-05-06','2012-09-20');
insert into assignments(case_id, officer_id, start_date, end_date) values (36,5,'2011-06-15',null);
insert into assignments(case_id, officer_id, start_date, end_date) values (37,2,'2012-01-09',null); 
insert into assignments(case_id, officer_id, start_date, end_date) values (38,8,'2012-10-09',null);
insert into assignments(case_id, officer_id, start_date, end_date) values (39,8,'2012-09-03',null); 
insert into assignments(case_id, officer_id, start_date, end_date) values (40,2,'2011-10-31',null);
insert into assignments(case_id, officer_id, start_date, end_date) values (41,8,'2012-09-18',null);
insert into assignments(case_id, officer_id, start_date, end_date) values (42,6,'2012-02-05',null);
insert into assignments(case_id, officer_id, start_date, end_date) values (42,2,'2012-02-05',null);
insert into assignments(case_id, officer_id, start_date, end_date) values (43,2,'2011-06-11',null);
insert into assignments(case_id, officer_id, start_date, end_date) values (44,8,'2011-10-25',null);
insert into assignments(case_id, officer_id, start_date, end_date) values (45,5,'2012-07-10',null);
insert into assignments(case_id, officer_id, start_date, end_date) values (46,2,'2012-08-25','2012-10-13');
insert into assignments(case_id, officer_id, start_date, end_date) values (47,2,'2011-08-23','2012-10-18');
insert into assignments(case_id, officer_id, start_date, end_date) values (48,6,'2012-06-26',null);
insert into assignments(case_id, officer_id, start_date, end_date) values (49,8,'2011-06-12',null);
insert into assignments(case_id, officer_id, start_date, end_date) values (50,9,'2012-04-10',null);

-- records for suspects
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (1,13,'2012-09-09','2012-10-01'); 
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (2,3,'2012-05-12','2012-08-01');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (3,2,'2012-06-26','2012-08-15');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (3,3,'2012-06-26','2012-08-15');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (4,6,'2012-08-12','2012-08-15');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (4,3,'2012-08-15','2012-08-30');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (5,8,'2012-07-15','2012-09-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (5,5,'2012-08-23','2012-09-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (6,2,'2012-06-24','2012-08-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (7,5,'2012-08-05','2012-09-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (8,2,'2012-08-15','2012-09-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (9,3,'2012-07-20','2012-10-01'); 
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (10,12,'2012-07-09','2012-09-01');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (10,3,'2012-08-01','2012-09-01'); 
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (11,3,'2012-08-12','2012-10-04');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (11,8,'2012-08-12','2012-10-04');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (12,7,'2012-08-22','2012-10-15');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (12,12,'2012-08-26','2012-10-15');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (13,6,'2012-05-09','2012-06-15');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (14,2,'2012-08-12','2012-08-30');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (15,5,'2012-04-20','2012-09-11');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (16,2,'2012-06-15','2012-07-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (17,8,'2011-06-14','2011-06-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (17,3,'2011-06-14','2011-06-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (18,5,'2012-10-12','2012-10-17');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (18,8,'2012-10-12','2012-10-17');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (19,1,'2011-12-07','2012-09-15');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (20,1,'2011-03-02','2012-01-04');	
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (21,9,'2011-12-09','2012-10-01'); 
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (22,11,'2011-08-15','2011-10-02');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (23,12,'2011-09-09','2011-10-01'); 
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (24,9,'2011-10-22','2011-12-01');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (26,13,'2012-09-12','2012-10-01');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (27,13,'2012-08-26','2012-10-15');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (28,9,'2011-12-13','2011-12-25');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (29,12,'2012-05-20','2012-08-30');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (30,11,'2012-04-15','2012-09-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (31,11,'2012-07-31','2012-09-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (32,9,'2011-07-14','2011-08-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (33,12,'2012-01-25','2012-03-14');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (34,2,'2012-07-05','2012-09-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (35,3,'2012-05-06','2012-09-20');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (36,7,'2011-06-15',null);
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (37,6,'2012-01-09',null); 
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (38,4,'2012-10-09',null);
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (39,6,'2012-09-03',null); 
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (40,6,'2011-10-31',null);
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (41,3,'2012-09-18',null);
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (42,2,'2012-02-05',null);
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (42,8,'2012-02-12',null);
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (43,3,'2011-06-11',null);
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (44,5,'2011-10-25',null);
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (45,2,'2012-07-10',null);
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (46,8,'2012-08-25','2012-10-13');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (47,1,'2011-08-23','2012-10-18');
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (48,3,'2012-06-26',null);
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (49,4,'2011-06-12',null);
insert into suspects(case_id, criminal_id, became_suspect_on, dropped_as_suspect_on) values (50,5,'2012-04-10',null);
